# tasks file for postfix
---

- name: set os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - default.yml

- include: "{{ ansible_distribution | lower }}.yml"

- name: configure mailname
  template:
    src: etc/mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags:
    - configuration
    - postfix
    - postfix-mailname

- name: update configuration file
  template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags:
    - configuration
    - postfix
    - postfix-configuration

- name: configure sasl username/password
  template:
    src: etc/postfix/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  when: postfix_relayhost != false
  notify:
    - postmap sasl_passwd
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-sasl-passwd

- name: configure aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:.*'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
  with_items: "{{ postfix_aliases }}"
  notify:
    - new aliases
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-aliases

- name: start and enable service
  service:
    name: postfix
    state: started
    enabled: true
  tags:
    - configuration
    - postfix
    - postfix-start-enable-service
