# Redhat-specific postfix tasks
---

- name: install package
  package:
    name={{ item }}
    state=present
  with_items: "{{ postfix_install }}"
  tags:
    - configuration
    - postfix
    - postfix-install
